name: Release
on:
  push:
  workflow_dispatch:

permissions: read-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prerelease
        id: prerelease
        uses: wearethefoos/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          create-prerelease: true

      - name: Release
        id: release
        uses: wearethefoos/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Versions
        id: print-versions
        run: |
          echo "prereleases: ${{ steps.prerelease.outputs.prereleases }}"
          echo "versions: ${{ steps.release.outputs.versions }}"
