name: Release
on:
  push:
  workflow_dispatch:

permissions: read-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-Release
        id: pre-release
        uses: wearethefoos/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          create-pre-release: true

      - name: Release
        id: release
        uses: wearethefoos/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Versions
        id: print-versions
        run: |
          echo "Pre-releases: ${{ steps.pre-release.outputs.versions }}"
          echo "Versions: ${{ steps.release.outputs.versions }}"
