name: 'Release'
description: 'Create semver releases based on conventional commits'
author: wearethefoos

branding:
  icon: heart
  color: red

inputs:
  token:
    description: 'GitHub token for authentication'
    required: true
  root-dir:
    description: 'The root directory to use for the release'
    required: false
    default: '.'
  manifest-file:
    description: 'The manifest file to use, relative to the root-dir'
    required: true
    default: '.release-manifest.json'
  create-prerelease:
    description: 'Whether to create prereleases from pull requests'
    required: false
    default: 'false'
  prerelease-label:
    description: 'The PR label to use for prereleases'
    required: false
    default: 'Prerelease'

outputs:
  version:
    description: 'The version that was released'
  prerelease:
    description: 'Whether the release was a prerelease'

runs:
  using: node20
  main: dist/index.js
