name: 'Release'
description: 'Create semver releases based on conventional commits'
author: wearethefoos

branding:
  icon: heart
  color: red

inputs:
  token:
    description: 'GitHub token for authentication'
    required: true
  root-dir:
    description: 'The root directory to use for the release'
    required: false
    default: '.'
  manifest-file:
    description: 'The manifest file to use, relative to the root-dir'
    required: true
    default: '.release-manifest.json'
  create-pre-release:
    description: 'Whether to create pre-releases from pull requests'
    required: false
    default: 'false'
  pre-release-label:
    description: 'The PR label to use for pre-releases'
    required: false
    default: 'Pre-Release'

outputs:
  version:
    description: 'The version that was released'
  pre-release:
    description: 'Whether the release was a pre-release'

runs:
  using: node20
  main: dist/index.js
