name: 'Release Monorepo Action'
description:
  'Create releases, prereleases, and changelogs based on conventional commits to
  multiple release targets.'
author: wearethefoos

branding:
  icon: package
  color: blue

inputs:
  token:
    description: 'GitHub token for authentication'
    required: true
  root-dir:
    description: 'The root directory to use for the release'
    required: false
    default: '.'
  manifest-file:
    description: 'The manifest file to use, relative to the root-dir'
    required: true
    default: '.release-manifest.json'
  create-prereleases:
    description: 'Whether to create prereleases from pull requests'
    required: false
    default: 'false'
  prerelease-label:
    description: 'The PR label to use for prereleases'
    required: false
    default: 'Prerelease'
  release-target:
    description:
      'The target environment to release to (e.g. main, canary, aws). Cannot be
      "latest"'
    required: false
    default: 'main'
  indentation:
    description:
      'The indentation to use for json files, can be "tab" or a number of
      spaces. Default is 2 spaces.'
    required: false
    default: '2'

outputs:
  releases-created:
    description: 'Whether one or more releases were created'
  version:
    description: 'The version that was released'
  versions:
    description: 'The versions that were released (e.g. from a monorepo)'
  prerelease:
    description: 'Whether the release or releases were prereleases'

runs:
  using: node20
  main: dist/index.js
