name: Release
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited
      - labeled
      - unlabeled
      - closed
      - reopened
      - locked
      - unlocked
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write # for adding labels to the PR

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        id: release
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          create-prereleases: true

      - name: Print Versions
        id: print-versions
        run: |
          echo "releases-created: ${{ steps.release.outputs.releases-created }}"
          echo "version: ${{ steps.release.outputs.version }}"
          echo "prerelease: ${{ steps.release.outputs.prerelease }}"

      - name: Push to major release branch
        id: push-to-major-release-branch
        if:
          steps.release.outputs.releases-created == 'true' &&
          steps.release.outputs.prerelease == 'false'
        run: |
          echo "Pushing to major and minor release tags and branches"

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          major_version=$(echo "${{ steps.release.outputs.version }}" | cut -d '.' -f 1)
          minor_version=$(echo "${{ steps.release.outputs.version }}" | cut -d '.' -f 2)
          major_release_tag="v$major_version"
          minor_release_tag="v$major_version.$minor_version"
          major_release_branch="releases/$major_release_tag"
          minor_release_branch="releases/$minor_release_tag"

          git tag "$major_release_tag" --force --annotate --message "Point $major_release_tag tag to ${{ steps.release.outputs.version }}"
          git tag "$minor_release_tag" --force --annotate --message "Point $minor_release_tag tag to ${{ steps.release.outputs.version }}"

          major_release_branch_exists=$(git ls-remote --heads origin "$major_release_branch")
          minor_release_branch_exists=$(git ls-remote --heads origin "$minor_release_branch")

          if [ -z "$major_release_branch_exists" ]; then
            git branch "$major_release_branch" "$major_release_tag"
            git push --set-upstream origin "$major_release_branch"
          fi

          if [ -z "$minor_release_branch_exists" ]; then
            git branch "$minor_release_branch" "$minor_release_tag"
            git push --set-upstream origin "$minor_release_branch"
          fi

          git push --follow-tags

          echo "Pushed to major and minor tags and release branches"
