name: Release
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited
      - labeled
      - unlabeled
      - closed
      - reopened
      - locked
      - unlocked
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write # for adding labels to the PR

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        id: release
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          create-prereleases: true

      - name: Print Versions
        id: print-versions
        run: |
          echo "releases-created: ${{ steps.release.outputs.releases-created }}"
          echo "version: ${{ steps.release.outputs.version }}"
          echo "prerelease: ${{ steps.release.outputs.prerelease }}"

      - name: Push to major release branch
        id: push-to-major-release-branch
        if:
          steps.release.outputs.releases-created == 'true' &&
          steps.release.outputs.prerelease == 'false'
        run: |
          echo "Pushing to major release branch"
          major_version=$(echo "${{ steps.release.outputs.version }}" | cut -d '.' -f 1)
          major_release_tag="v$major_version"
          major_release_branch="releases/$major_release_tag"

          major_release_branch_exists=$(git ls-remote --heads ${{ github.repositoryUrl }} $major_release_branch)

          if [ -z "$major_release_branch_exists" ]; then
            git branch "$major_release_branch" "$major_release_tag"
            git push --set-upstream ${{ github.repositoryUrl }} "$major_release_branch"
          fi

          echo "Pushed to major release branch"
